name: Update DB

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"
    
env:
  CLIENT_ID: ${{ secrets.CLIENT_ID }}
  CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
    
permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tqdm
        pip install requests
    - name: Run script
      run: |
        cd server/
        python gen_list.py
        cd ..
        python wcl_ant.py
        python bump_version.py
